#!/bin/bash
# Deploy Apex Action: AccountTierLookupAction
# Generated by /agentforce:build-apex-action
# Usage: ./deploy.sh <org-alias>

set -e
ORG=${1:-"my-org"}

echo "=== Deploying Apex Action: AccountTierLookupAction ==="
sf project deploy start \
  --source-dir force-app/main/default/classes/ \
  --target-org "$ORG"

echo ""
echo "=== Running Tests ==="
sf apex run test \
  --class-names AccountTierLookupActionTest \
  --result-format human \
  --target-org "$ORG" \
  --wait 10

echo ""
echo "=== Deployment complete ==="
