#!/bin/bash
# Deploy Agent: SampleSaaSAgent
# Generated by /agentforce:design-agent
# Usage: ./deploy.sh <org-alias>

set -e
ORG=${1:?"Usage: ./deploy.sh <org-alias>"}

echo "=== Deploying SampleSaaSAgent ==="
sf project deploy start \
  --source-dir force-app/ \
  --target-org "$ORG"

echo ""
echo "=== Deployment complete ==="
echo "Open Agent Builder to verify: Setup → Agents → SampleSaaSAgent"
